openapi: 3.0.3
info:
  version: 1.0.0
  title: Swagger sample @zenn article
tags:
  - name: common
    description: 共通領域
  - name: order
    description: 申込領域
paths:
  GetSystemDateTime:
    get:
      tags:
        - common
      summary: システム日時取得API
      description: |-
        [Overview]

        サーバ内システム日時を[yyyy-MM-dd HH:mm:ss](JST)形式で返却する

        [Details]

        1.システム日時を返却する
        - 1-1. 設定ファイルに保存されている値が存在する場合、その日時を返却する
      operationId: GetSystemDateTime
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: object
                properties:
                  SystemDateTime:
                    type: string
                    description: システム日時
                    format: date-time
                    example: '2023-09-22 09:22:22'
        '500':
          $ref: '#/components/InternalServerErrorResponse'
  PostCreateOrder:
    post:
      tags:
        - order
      summary: 申込作成API
      description: |-
        [Overview]
        申込情報を作成し外部APIをCallする
        [Details]
        1.requestBodyから「リクエスト項目」を取得する。
        2.requestBodyをリクエスト項目として、外部APIをコールする。
      operationId: PostCreateOrder
      requestBody:
        description: リクエスト項目を指定
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderid:
                  title: 申込ID
                  type: string
                  example: Order0001
                userid:
                  title: ユーザID
                  type: string
                  example: User0001
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: object
                properties:
                  processResult:
                    $ref: '#/components/ProcessResultModel'
        '500':
          $ref: '#/components/InternalServerErrorResponse'
components:
  ProcessResultModel:
    type: object
    description: c-map処理結果用モデル
    properties:
      returnCode:
        type: string
        description: リターンコード
        example: Success
      resultInfos:
        type: array
        items:
          type: object
          description: 結果情報リスト
          properties:
            resultCategory:
              type: string
              description: 結果区分
              example: Error
            resultCode:
              type: string
              description: 結果コード
              example: XXXXX
            resultMessage:
              type: string
              description: 結果メッセージ
              example: XXXXX
  ErrorModel:
    description: Response Error Model.
    required:
      - StatusCode
      - Message
    type: object
    properties:
      StatusCode:
        title: StatucCode
        type: integer
        format: int32
        example: 500
      Message:
        title: statuscode of name
        type: string
        example: Internal Server Error.
      ValidationErrors:
        type: array
        description: ValidationErrors
        items:
          type: object
          properties:
            Code:
              title: メッセージコード
              type: string
              example: null
            Message:
              title: メッセージ
              type: string
              example: null
            Attribute:
              title: 項目
              type: string
              example: null
      BusinessErrors:
        type: array
        description: BusinessErrors
        items:
          type: object
          properties:
            Code:
              title: メッセージコード
              type: string
              example: null
            Message:
              title: メッセージ
              type: string
              example: null
            Attribute:
              title: 項目
              type: string
              example: null
  InternalServerErrorResponse:
    description: Internal Server Error.
    content:
      application/json:
        schema:
          allOf:
            - $ref: '#/components/ErrorModel'
          properties:
            StatusCode:
              example: 500
            Message:
              example: Internal Server Error.
